### ISSUE TITLE
Tesseract 4 LSTM (--oem 1)

### ISSUE THREAD

**Issue by gabriel-v** [LeoFCardoso/pdf2pdfocr#13]
Is there a flag to set `--oem 1` in for tesseract 4 like documented [here](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#available-ocr-engines-in-tesseract-4)?

**Comment by LeoFCardoso** [comment]
Hello. Not yet. I will code this in context of this ticket.
