### ISSUE TITLE
Specify Output Folder using pdf2pdfocr.vbs

### ISSUE THREAD

**Issue by der-klabauter** [LeoFCardoso/pdf2pdfocr#14]
Dear Leo,

I love your project but would like to directly push the OCRed files to a new directory.
Therefor I tried to add amend the defaultoptions:  default_option = "-stp -j 0.9 -o %Userprofile%" 
But no matter which directory I add, I always get a permission error:

Traceback (most recent call last):
  File "C:\Users\Christoph\pdf2pdfocr-venv\Scripts\pdf2pdfocr.py", line 1249, in <module>
    pdf2ocr.ocr()
  File "C:\Users\Christoph\pdf2pdfocr-venv\Scripts\pdf2pdfocr.py", line 605, in ocr
    self.initial_cleanup()
  File "C:\Users\Christoph\pdf2pdfocr-venv\Scripts\pdf2pdfocr.py", line 952, in initial_cleanup
    Pdf2PdfOcr.best_effort_remove(self.output_file)
  File "C:\Users\Christoph\pdf2pdfocr-venv\Scripts\pdf2pdfocr.py", line 1154, in best_effort_remove
    os.remove(filename)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\Christoph'

Any ideas how to fix it?

Thank you so much.

BR
Christoph

**Comment by LeoFCardoso** [comment]
Hello, thanks for the post.
Please note that -o require a filename and not a destination directory. Please adjust your script to specify a file, instead of folder, maybe:
-o %Userprofile%\final-file-ocred.pdf

**Comment by LeoFCardoso** [comment]
Humm. I think I got your point. Are you using VBS for multiple files and would like just to specify a different folder for them all, keeping the original file name, right?

**Comment by der-klabauter** [comment]
Yep, that was the idea. I wanted to push the files directly to my NAS after OCR. In the current configuration this is not that simple because I would need to extract the filenames in the vbs script.
It would be great if you could add a flag in pdf2pdfocr.py that allows to modify the output path while keeping the filenames.

**Comment by LeoFCardoso** [comment]
I will create this use case.
By now, you can work with current directory and copy files manually to your NAS using the default file output name. Do not use "-o", let pdf2pdfocr create result files in current folder and then issue:
"move *-OCR.pdf <<NAS PATH>>".

**Comment by LeoFCardoso** [comment]
@der-klabauter please let me know if it works for you.

**Comment by der-klabauter** [comment]
works well, thanks :)
