### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ericmoret** [LeoFCardoso/pdf2pdfocr#16]
I found out that following the macports installation documentation did not properly install the modules with pip. In order to make it work, I had to use pip3 such as:
```
sudo pip3 install reportlab Gooey
sudo pip3 install https://github.com/mstamy2/PyPDF2/archive/master.zip
sudo pip3 install lxml beautifulsoup4
```

**Comment by LeoFCardoso** [comment]
Hi @ericmoret , thanks for your message.
Did you try 
`sudo port select --set pip pip37`
before?

**Comment by ericmoret** [comment]
I did follow all the steps documented for Macs on 2 separate computers both running Catalina 10.15.4 and twice had to issue that pip3 command instead.

**Comment by LeoFCardoso** [comment]
Ok, I'll fix this soon. Thanks.
