### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by ericmoret** [LeoFCardoso/pdf2pdfocr#18]
It would be nice for the installation script to create an icon for the gui that would appear as an Application. This would allow running without starting the terminal.

**Comment by LeoFCardoso** [comment]
Hi Eric!
Please consider create macos App using Automator.
Here's a sample screen shot (portuguese)
<img width="983" alt="Captura de tela 2020-04-11 13 00 30" src="https://user-images.githubusercontent.com/1037439/79048577-89a8d000-7bf4-11ea-9f84-80bbc0d00ac1.png">

**Comment by ericmoret** [comment]
Great suggestion, I actually used your script from [GUI #6](https://github.com/LeoFCardoso/pdf2pdfocr/issues/6) with slight changes for zsh which is now default in macos Catalina:
```
source /etc/zprofile
source $HOME/.zprofile

for f in "$@"
do
	/usr/local/bin/pdf2pdfocr.py -st -i "$f"  
done
```
<img width="1042" alt="Screen Shot 2020-04-11 at 9 45 57 AM" src="https://user-images.githubusercontent.com/15149801/79049575-4e4cd800-7bd9-11ea-9cf2-54d3f4b07695.png">

**Comment by LeoFCardoso** [comment]
I'm closing this as we have a good workaround using automator.
