### ISSUE TITLE
what does cmd_file implies

### ISSUE THREAD

**Issue by Harish202** [LeoFCardoso/pdf2pdfocr#19]
cmd_file = 'file', may I know the intuition of this variable. Its path is always getting as None and I am not sure if we need to hard code it to some value or did I miss something during installation?

I have installed everything on windows.

**Comment by LeoFCardoso** [comment]
Hi, this is to detect mime types on input files, using "file" command in POSIX systems.
In Windows you have to install "file" and make dure its callable from path.
Did you use the "install windows" tutorial using scoop?

**Comment by Harish202** [comment]
Hey LeoFCardoso,

Thank you for quick reply, my bad its working now. I am closing the issue
