### ISSUE TITLE
file already has text and check text mode is enabled. Exiting.

### ISSUE THREAD

**Issue by icegood** [LeoFCardoso/pdf2pdfocr#2]
Hi, i've obtained next error while trying to add ocr to pdf:
 --> Errors/Warnings:
<my file> already has text and check text mode is enabled. Exiting.

You may find 'wrong' pdf from google drive:
https://drive.google.com/open?id=0B4mLkzBXmYycQ2N5OGpneWd5dzQ

**Comment by LeoFCardoso** [comment]
Hi Icegood.
What OS are you using?
Which command line flags did you use?
Please check you are **not** using "-t" flag. 
For example: pdf2pdfocr.py -i ./file.pdf

**Comment by LeoFCardoso** [comment]
Closing this issue as it seems that "-t" flag was incorrectly used.

**Comment by icegood** [comment]
Sorry, Leo. Had no time to respond. I don't use any flags. Only -i. Have you checked file that i shared above? You cannot convert even without -t flag.

**Comment by LeoFCardoso** [comment]
I could convert the file by just using "-i" flag. I'm reopening the issue as it's not working to you.
Please inform:
OS that you are using?
Python version?
Complete command line used?
All messages generated in stdout?

Thanks!

**Comment by icegood** [comment]
OS: Windows 10 x64
Python version : Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49)
other tools: tesseract-ocr-setup-3.05.01
gs9.22
ImageMagick-7.0.7-Q16 x64

run via pdf2pdfocr.vbs script.

Now i see on screen that "Use <Enter> for default [-stp -j 0.9] or <.> for last used option []."
so -t was default. 
Please, close bug as it not valid anymore.

**Comment by LeoFCardoso** [comment]
Great!
