### ISSUE TITLE
the right edge of the text is not fully highlighted

### ISSUE THREAD

**Issue by derrikF** [LeoFCardoso/pdf2pdfocr#23]
Hello

in pdf, after recognition with pdf2pdfocr_gui.py, the right edge of the text is not fully highlighted if you select 'tesseract' for the '- e' option.
and if you select 'native', then the entire text is highlighted correctly,but there are no Cyrillic characters.
see the screenshots...

if you say that this is a tesseract problem, then this is incorrect, because I recognize djvu with 'ocrodjvu' and the text is highlighted correctly after recognition.

can this be corrected?
<a target="_blank" href="https://d.radikal.ru/d13/2011/0b/69775c4f50e8.png"><img src="https://d.radikal.ru/d13/2011/0b/69775c4f50e8t.jpg" /></a>

<a target="_blank" href="https://a.radikal.ru/a15/2011/ba/408ab96860b3.png"><img src="https://a.radikal.ru/a15/2011/ba/408ab96860b3t.jpg" /></a>

**Comment by LeoFCardoso** [comment]
Can you attach the input PDF?

**Comment by derrikF** [comment]
> Can you attach the input PDF?

[2020-11-07.pdf](https://github.com/LeoFCardoso/pdf2pdfocr/files/5508824/2020-11-07.pdf)

**Comment by LeoFCardoso** [comment]
I got some kind of success with this command:

`pdf2pdfocr.py -i 2020-11-07.pdf -l rus -v -f -g best`

But this rebuild the original PDF, as without "-f" I'm receiving some kind of exception.

I will check in more depth. What's the page number you see the issue?

**Comment by derrikF** [comment]
I apologize, but this seems to be a problem with those programs that open pdf. other programs highlight the text correctly. you need to change the default pdf-viewer.

the only thing missing in your tool is to specify the page range, and not run through the entire document. and so great tool with GUI

or you can use "--page=" for "-x" ?

On Linux - Evince, FoxitReader - incorrectly highlight the text, WPS Rader, Master PDF Editor 5 - correctly

**Comment by LeoFCardoso** [comment]
I will check this suggestion and try to implement page range flag.
"-x" will not work as it would be passed to all pages.
Thank you for your issue.

**Comment by LeoFCardoso** [comment]
Issue fixed in last commit. Page range added to roadmap. Thank you!
