### ISSUE TITLE
Multiple Files Together

### ISSUE THREAD

**Issue by mananchawla2005** [LeoFCardoso/pdf2pdfocr#28]
Hey is there any option to ocr multiple files together ( or any script that I can use). Doing one by one takes alot of time. Thanks for this awesome tool btw!

**Comment by LeoFCardoso** [comment]
Hi, sorry for the late answer.
Are you using Windows? If so, please check the VBS script.

**Comment by LeoFCardoso** [comment]
Hi @mananchawla2005 , please check last version as "-i" parameter now can be a folder.

**Comment by LeoFCardoso** [comment]
https://github.com/LeoFCardoso/pdf2pdfocr/commit/22d7dc8990df38d2873b1a0b0f966df5d778a1f6

**Comment by mananchawla2005** [comment]
Heyyy thanks!! I will check and get back to you. Thanks again!
