### ISSUE TITLE
merging multiple files into one pdf-file

### ISSUE THREAD

**Issue by tfinke18119** [LeoFCardoso/pdf2pdfocr#32]
At the moment, a pdf file is created for each file if the option "-i" is used for a directory. There should be an option that packs all the files into one single pdf file. This would be a useful option if there were several "edited" image files (e.g. processed with scantailor) in that directory after a scan (e.g. one for each page). An option for the "correct" sorting these pages has to be kept in mind as well.

**Comment by LeoFCardoso** [comment]
Hello @tfinke18119 , thanks for the issue.
Did you try "pdfunite" from poppler?

**Comment by tfinke18119** [comment]
There are several tools to unite pdfs, like sejda, pdfsam, pdftk etc. I just thought that a corresponding option for pdf2pdfocr would give more sense to the "-i" option.

**Comment by tfinke18119** [comment]
qpdf seems to be more sensible because it has more options.
