### ISSUE TITLE
PyPDF2 moved PdfReadError from utils to errors

### ISSUE THREAD

**Issue by Cragsand** [LeoFCardoso/pdf2pdfocr#35]
Followed the instruction guide for Windows and noticed an error when running the SendTo VBScript
"ModuleNotFoundError: No module named 'PyPDF2.utils'"

Looks like the latest version of PyPDF2 moved PdfReadError from utils to errors

Changing line 41 from
```
from PyPDF2.utils import PdfReadError
```
to
```
from PyPDF2.errors import PdfReadError
```
fixed the problem.

![bild](https://user-images.githubusercontent.com/49168045/194845080-b30cc289-2151-4082-9c52-8e6d5cb5ce54.png)

Cheers

**Comment by LeoFCardoso** [comment]
Thank you. I'll fix the Windows tutorial and check de dependencies.

**Comment by LeoFCardoso** [comment]
Fixed in https://github.com/LeoFCardoso/pdf2pdfocr/commit/cf759bab9ef7e86a50e539389775d630a09a5e13
