### ISSUE TITLE
 pdf2pdfocr changing languages

### ISSUE THREAD

**Issue by Cragsand** [LeoFCardoso/pdf2pdfocr#36]
This wasn't included in the readme file but some info for anyone else lost.
You can change the language model to download by editing this:
```aria2c "https://github.com/tesseract-ocr/tessdata/blob/main/por.traineddata?raw=true" --dir="%TESSDATA_PREFIX%"```
And change the language prefix to which language you want. As long as its available on the tesseract repo. For example here is Swedish - "swe":
![bild](https://user-images.githubusercontent.com/49168045/194847930-fc81a6e0-3143-4c69-9874-c27bc8b64c50.png)

Further info here:
https://github.com/tesseract-ocr/tesseract/blob/main/doc/tesseract.1.asc#LANGUAGES 

To change default language edit pdf2pdfocr.py on line 548 from Portuguese + English - "por+eng" to whichever. For me I use Swedish + English - "swe+eng"
```self.tess_langs = "por+eng"  # Default```
to 
```self.tess_langs = "swe+eng"  # Default```

For example to get Swedish 
![bild](https://user-images.githubusercontent.com/49168045/194847498-442ec62e-564b-4380-98ff-68810cff501c.png)

**Comment by LeoFCardoso** [comment]
Thank you.
"por+eng" is the default because I'm from Brazil.
You can also use "-l" flag to set the language in each execution.
