### ISSUE TITLE
A rectangular block is the only portion being selected from within a paragraph.

### ISSUE THREAD

**Issue by yatrik-cloud** [LeoFCardoso/pdf2pdfocr#42]
As you can see in the below image, 
any solution to this problem?
![image](https://github.com/LeoFCardoso/pdf2pdfocr/assets/144119244/eed94b30-9f08-44db-a888-0222b6379679)

**Comment by LeoFCardoso** [comment]
Hello, thank you again for the issue.

In this case, I need the source PDF for debug.

Can you please share it here?

**Comment by yatrik-cloud** [comment]
1. 
This is that pdf :
[Dummy_IS.pdf](https://github.com/LeoFCardoso/pdf2pdfocr/files/12573938/Dummy_IS.pdf)

2. 
![image](https://github.com/LeoFCardoso/pdf2pdfocr/assets/144119244/cec5cbb0-c11b-4a4d-b48b-7a2e424f6b54)

This is one more example of the same ...

3. 
pdf2pdfocr sometimes does not work well on the tabular data.

These are the issues so kindly check these, and get back to me ...

**Comment by LeoFCardoso** [comment]
Hello. I couldn't reproduce the bug. Here's the result using Adobe reader and "-r 200". 

<img width="1190" alt="image" src="https://github.com/LeoFCardoso/pdf2pdfocr/assets/1037439/fb83290d-385f-4325-a09f-87b96182f9a5">

<img width="1150" alt="image" src="https://github.com/LeoFCardoso/pdf2pdfocr/assets/1037439/d8e20a87-b6ce-4a50-9561-5755807a589b">

Please run this file with "-v" (verbose) and send me the entire texto output generated.
Also, please inform your operating system.

**Comment by yatrik-cloud** [comment]
solved the bug using "-r 200", and output in Adobe reader.
Thank you.
