### ISSUE TITLE
file not found. Aborting...

### ISSUE THREAD

**Issue by yatrik-cloud** [LeoFCardoso/pdf2pdfocr#43]
python pdf2pdfocr.py -v -r 200 -i Dummy_IS_4.pdf
-------------------------------------
File: Dummy_IS_4.pdf
[2023-09-14 11:37:30.229202] [DEBUG] Tesseract can 'textonly_pdf': True
[2023-09-14 11:37:30.247081] [DEBUG] Tesseract version: 5
[2023-09-14 11:37:30.247081] [DEBUG] cuneiform not available
file not found. Aborting...

In GUI:
![image](https://github.com/LeoFCardoso/pdf2pdfocr/assets/144119244/0cd03571-52a4-4206-8c93-2c9a406d503a)

**Comment by LeoFCardoso** [comment]
Hi!
Please try to use complete path instead of just the filename.

**Comment by yatrik-cloud** [comment]
> Hi! Please try to use complete path instead of just the filename.

I have tried it also,
it's also not working.

I also tried to choose the file by using the 'browse' button, available in the GUI, to take the path directly,
also not working.
