### ISSUE TITLE
How to use this directly without docker on windows 11?

### ISSUE THREAD

**Issue by yatrik-cloud** [LeoFCardoso/pdf2pdfocr#44]
How can I use this tool directly on Windows 11 without Docker? 
I'd like to utilize it as a python function API that accepts arguments and generates the OCR'd file.

**Comment by LeoFCardoso** [comment]
Hi!
I don't know if I understand this issue.
Please read "install_windows.txt" file and try the tutorial with scoop tool.

**Comment by yatrik-cloud** [comment]
Okay, thanks.
I appreciate your active contribution as an open-source contributor.
Can you give me your LinkedIn?

**Comment by LeoFCardoso** [comment]
@yatrik-cloud , thank you.
Here's my LinkedIn: https://www.linkedin.com/in/leonardo-cardoso-990444a
