### ISSUE TITLE
Do we have any parameter / flag for pdf compression here, to reduce pdf size after applying OCR?

### ISSUE THREAD

**Issue by yatrik-cloud** [LeoFCardoso/pdf2pdfocr#48]

**Comment by LeoFCardoso** [comment]
Hello @yatrik-cloud.
There's no such flag for PDF compression.
But you can emulate it using image processing ("-f") and some image reduction strategy.
First, please use "-f" and "-r 200" to reduce image resolution and this should reduce size.
Also, try to play with "-g" parameters.

**Comment by yatrik-cloud** [comment]
"-f" is changing pdf image color, a gray scale image to black/white binary image

**Comment by LeoFCardoso** [comment]
Yes, this is expected.
That’s why you should use “-f” combined with some “-g” option.

**Comment by LeoFCardoso** [comment]
Old issue, marking as done due to lack of response.
