### ISSUE TITLE
Error/Warning: Mogrify from ImageMagick not found. Aborting ...

### ISSUE THREAD

**Issue by rubenkr** [LeoFCardoso/pdf2pdfocr#5]
Hi there,

I always was looking for an open source tool suite like yours. I installed everything as explained for Windows7x64 system according to your README.

Right Click on PDF -> Send To -> VBS Script gives the error from above

However mogrify is installed. As I can run it from command line with "magick mogrify" successfully.

Looking into the python code it looks that it should work. Can you help me out?

Thank you so much.

**Comment by LeoFCardoso** [comment]
Hi there. Let's try some troubleshooting.
Please let me know if you are using exactly the software versions suggested in readme file.
To test mogrify, you should run "mogrify" in cmd, not "magick mogrify".
When installing ImageMagick, please make sure you add tools to system path, and install "legacy" command line params.

**Comment by rubenkr** [comment]
Hi there, thanks for the fast reply. I now installed both x64/x86 version as in the ODT file. And a different error message appairs: "File not found" and it says "Processing C:\Users\user\Desktop\test.pdf ..". Is this maybe some string formatting problems on my machine?

**Comment by LeoFCardoso** [comment]
Hi there, let's try this:
1) uninstall / delete all external tools (32 and 64 bit).
2) install 64 bit version of tools whenever possible (ghostscript, imagemagick, python);
3) install 32 bit version of the other tools that doesn't have a 64 bit port (file, pdftk, poppler, tesseract).

Make sure of file paths are correct.

**Comment by rubenkr** [comment]
Hi Leo,
I tried steps 1 to 3. Had to reinstall via pip reportlab and pypdf2. Still I get the same error message "no file found". Trying to rename filename without blank spaces. Unchanged. Definitely this project I will watch closely and hopefully at some stage it works also for me. Keep up the great work.

**Comment by LeoFCardoso** [comment]
Hi Rubenkr, please open a command prompt and issue this command:

> "%USERPROFILE%\pdf2pdfocr\pdf2pdfocr.py"

What do you got? The help file?

If it works, please add some PDF file to OCR:

> "%USERPROFILE%\pdf2pdfocr\pdf2pdfocr.py" -i -somePDFFile-

Please post the results.

**Comment by LeoFCardoso** [comment]
Please try to install in Windows with new instructions (scoop tool).

**Comment by LeoFCardoso** [comment]
I'm closing this issue now. Please add another if there are problems with Windows installation through scoop.
