### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ericmoret** [LeoFCardoso/pdf2pdfocr#6]
Would be nice to have a simple gui to this tool. Maybe a contextual menu in finder, a print driver, or even an icon that could accept dragged and dropped pdf files ready to OCR?

**Comment by sky4055** [comment]
@ericmoret +1

**Comment by LeoFCardoso** [comment]
Hi there! Thanks for the suggestion. I will try to build something multiplatform.
By now, in MacOS you can try Automator. I have a "workflow" with this script:

```
source /etc/profile
source /Users/XXXXX/.profile   # Use your username
#
for f in "$@"
do
	/usr/local/bin/pdf2pdfocr.py -st -i "$f"  
done
```
You can create various workflows with different PDF2PDFOCR parameters.
It's not a GUI, so this issue stay open, but maybe it can work for you.

**Comment by LeoFCardoso** [comment]
Last commit introduce a simple GUI using Gooey library.
Please install Gooey from PIP and have a try.
Tested on MacOS and Windows.

**Comment by LeoFCardoso** [comment]
Please open new issues for GUI related features.
